### ISSUE TITLE
Add support for a special file to exclude a directory from being rendered

### ISSUE THREAD

**Issue by onedr0p** [mirkolenz/makejinja#102]
**Is your feature request related to a problem? Please describe.**

I have request that would reduce some logic needed in files if a var is not true. In [this](https://github.com/onedr0p/flux-cluster-template/tree/5a90397ed563f8ddb18694a143cd5705dc600ab2/bootstrap/templates/kubernetes/talos) directory all files are wrapped with an if statement of `if bootstrap_distribution == 'talos'`. If you take a look around the `./bootstrap/templates` folder you will see I am doing this quite a bit to exclude folders and files from being templated based on variables.

**Describe the solution you'd like**

I was thinking it would be cool to support like a `.pathignore.j2` file where the contents would hold the logic if that folder, subfolders and files get templated. I could drop this file in `./bootstrap/templates/kubernetes/talos` and omit the logic in the files.

```j2
{% bootstrap_distribution == 'talos' %}
```

I am not sure if this can be done in custom Loader but I am all ears if there is already a way to do this but needs some special sauce added on my end.

**Comment by mirkolenz** [comment]
Thanks for the suggestion, I think your use-case is totally valid! I feel that the most "elegant" way of implementing such a feature would be to extend of the loader class with support for dynamic exclusions (i.e., allowing users to supply a function with type `Callable[[Path], bool]` that receives the currently processed input path returns `True` to continue processing or `False` to skip it. This also has the advantage that one has access to standard Python code for the checks and that all exclusions are defined centrally. I will try to come up with an early version of this as soon as possible.

**Comment by onedr0p** [comment]
That sounds like it could work. I might need to see an example of the implementation to wrap my brain around it. No rush on this, the currently method of having `if` statements in each files works for now but as my repo grows it's going to get a little cumbersome.

**Comment by mirkolenz** [comment]
My idea is to allow something like this:

```python
from pathlib import Path


class Loader:
    def __init__(self, data) -> None:
        self.data = data

    def filter_path(self, path: Path) -> bool:
        if (
            str(path).startswith("bootstrap/templates/kubernetes/talos")
            and self.data.bootstrap_distribution == "talos"
        ):
            return False

        return True
```

**Comment by mirkolenz** [comment]
Or maybe the following (which would be more in line with the existing members of the loader class):

```python
from pathlib import Path


class Loader:
    def __init__(self, data) -> None:
        self.data = data

    def path_filters(self):
        return [self._filter_talos]

    def _filter_talos(self, path: Path) -> bool:
        if (
            str(path).startswith("bootstrap/templates/kubernetes/talos")
            and self.data.bootstrap_distribution == "talos"
        ):
            return False

        return True

```

**Comment by onedr0p** [comment]
That's much better than the solution I came up with and makes it very extendable!

**Comment by onedr0p** [comment]
Hey @mirkolenz after thinking on this for the past day it would still be neat to support my original request of a "special file", let me explain.

The major benefit I see to having support for this is I don't need to manage the Loader on if/when paths are remove or changed. I could keep the logic coupled to the folder where the files are located. I have a lot of directories that could make use of a feature like this and having it wired into the loader file will increase the maintenance burden on my end to make sure that file is updated, also it might cause issues on if paths are changed and the loader it not updated.

**Comment by mirkolenz** [comment]
I see! I will keep the decentralized use case in mind when designing the solution and provide you with a code example how to apply it to your use case.

**Comment by mirkolenz** [comment]
Here is a draft for a loader that could support this with not-yet-released changes in makejinja:

```python
from collections.abc import Callable
from pathlib import Path
from typing import Any

import makejinja
from jinja2.utils import import_string


class Loader:
    def __init__(self, data: dict[str, Any], config: makejinja.config.Config):
        self.data = data
        self.config = config

        self._excluded_dirs: set[Path] = set()

        for input_path in config.inputs:
            for filter_file in input_path.rglob(".mjfilter"):
                filter_func: Callable[[dict[str, Any]], bool] = import_string(
                    f"{filter_file}:main"
                )
                if filter_func(data) is False:
                    self._excluded_dirs.add(filter_file.parent)

    def path_filters(self):
        return [self._mjfilter_func]

    def _mjfilter_func(self, path: Path) -> bool:
        # Render the file if there is no parent directory that is excluded
        return not any(
            path.is_relative_to(excluded_dir) for excluded_dir in self._excluded_dirs
        )

```

- The `__init__` function now receives the complete config so that things like the input folders are available.
- The loader then recursively searches for any file `.mjfilter` (just an example) in each input path.
- Such a `.mjfilter` is a Python file that should contain a function `main` (may be changed) that receives the data dict and returns True if the folder contents shall be rendered and False if it shall be skipped.
- The functions are then evaluated and each Path returning False is saved to a set.
- The path filter then checks if the current file is contained in an excluded folder and consequently returns False in this case.

This is obviously not finalized, I just wanted to ask for your feedback before doing the actual implementation. What do you think?

**Comment by mirkolenz** [comment]
For completeness, here is an example for a `.mjfilter` file:

```python
def main(data):
    return data["bootstrap_distribution"] == "talos"
```

That would render the folder only if `bootstrap_distribution` is `talos`. To reverse the logic, one can use `!=`.

**Comment by onedr0p** [comment]
Using python over jinja makes a ton of more sense, I can't wait to try it out!

**Comment by mirkolenz** [comment]
The mentioned changes are now live: https://github.com/mirkolenz/makejinja/releases/tag/v2.4.0

The code snippet provided by me should still hold. The only thing to keep in mind is that the `.mjfilter` files should probably be added to `--exclude-pattern`, otherwise they will be copied over.

Please let me know if the code works as expected. Also check whether the runtime is negatively impacted by adding path filters. Depending on the logic, it may have a huge impact since the functions are called for every file and directory that is matched by the `--include-pattern`. That is the reason why in my code example, the excluded paths are added to a set: To minimize runtime impact.

In the new version, I changed the default for `--keep-trailing-newlines` to true, so one needs to set `--strip-trailing-newlines` for the old behavior. It also means that this setting may be removed from your `makejinja.toml` if you would like to.

Lastly, I would like to note that I renamed "loaders" to "plugins" since that more closely resembles what they are actually used for. It also makes it easier for users to differentiate between the Jinja loaders and the makejinja plugins. This change should be backwards-compatible (i.e., I added aliases for all deprecated names like AbstractLoader and so on). If something breaks with the new version then I consider this to be a bug that should be fixed.

**Comment by onedr0p** [comment]
2.5.0 looks good! I was able to migrate over to the Plugins without an issue.

However I am having trouble with implementing the mjfilters, I tried following along with what you posted eariler.

More information here: https://github.com/onedr0p/flux-cluster-template/pull/1222

**Comment by mirkolenz** [comment]
Ok so the problem is that Jinja's `import_string` expects a module name like `path.to.file`, but it receives a path like `path/to/file` instead. This dot-based notation means that the filter files need to follow Python file naming conventions, so you need to rename them to something like `_mjfilter.py`. I currently do not have the time to test it, but does the following work with these modifications?

```python
from collections.abc import Callable
from pathlib import Path
from typing import Any

import makejinja
from jinja2.utils import import_string


class Plugin:
    def __init__(self, data: dict[str, Any], config: makejinja.config.Config):
        self.data = data
        self.config = config

        self._excluded_dirs: set[Path] = set()

        for input_path in config.inputs:
            for filter_file in input_path.rglob("_mjfilter.py"):
                filter_file = filter_file.relative_to(Path.cwd())
                filter_file = filter_file.with_suffix("")
                filter_module = str(filter_file).replace("/", ".")
                filter_func: Callable[[dict[str, Any]], bool] = import_string(
                    f"{filter_module}:main"
                )
                if filter_func(data) is False:
                    self._excluded_dirs.add(filter_file.parent)

    def path_filters(self):
        return [self._mjfilter_func]

    def _mjfilter_func(self, path: Path) -> bool:
        # Render the file if there is no parent directory that is excluded
        return not any(
            path.is_relative_to(excluded_dir) for excluded_dir in self._excluded_dirs
        )

```

If it does not work, you need to modify how the module name is constructed (i.e., all lines where `filter_file` and `filter_module` is assigned some value).

If you do not get it to work, could you maybe assemble a minimal working example that I can tinker with and upload it as a ZIP file? That would greatly help me in constructing the right code.

**Comment by onedr0p** [comment]
I can't even get this line to work 😄 

```python
class Plugin(makejinja.plugin.Plugin):
    def __init__(self, data: dict[str, Any], config: makejinja.config.Config):
        self.data = data
        self.config = config
```

## Logs

```
Traceback (most recent call last):
  File "/Users/devin/Code/repos/onedr0p/flux-template-cluster/.venv/bin/makejinja", line 8, in <module>
    sys.exit(makejinja_cli())
             ^^^^^^^^^^^^^^^
  File "/Users/devin/Code/repos/onedr0p/flux-template-cluster/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/devin/Code/repos/onedr0p/flux-template-cluster/.venv/lib/python3.11/site-packages/rich_click/rich_command.py", line 126, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/devin/Code/repos/onedr0p/flux-template-cluster/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/devin/Code/repos/onedr0p/flux-template-cluster/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/devin/Code/repos/onedr0p/flux-template-cluster/.venv/lib/python3.11/site-packages/typed_settings/cli_click.py", line 247, in new_func
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/devin/Code/repos/onedr0p/flux-template-cluster/.venv/lib/python3.11/site-packages/makejinja/cli.py", line 37, in makejinja_cli
    makejinja(config)
  File "/Users/devin/Code/repos/onedr0p/flux-template-cluster/.venv/lib/python3.11/site-packages/makejinja/app.py", line 60, in makejinja
    plugins.append(load_plugin(plugin_name, env, data, config))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/devin/Code/repos/onedr0p/flux-template-cluster/.venv/lib/python3.11/site-packages/makejinja/app.py", line 358, in load_plugin
    env.globals.update(plugin.data())
                       ^^^^^^^^^^^^^
TypeError: 'dict' object is not callable
```

**Comment by onedr0p** [comment]
Actually I renamed these and it seems to have gotten pass that error. Maybe some shadowing happening.

```
    def __init__(self, data: dict[str, Any], config: makejinja.config.Config):
        self.user_data = data
        self.user_config = config
```

**Comment by onedr0p** [comment]
If/when you have a moment I included a minimum example of what I am trying to achieve here, you should just be able to change config in `bootstrap/vars/config.yaml` and then run `makejinja` to test.

https://github.com/onedr0p/makejinja-mjfilter-example

**Comment by mirkolenz** [comment]
Thanks for the MWE, I will investigate as soon as I have some spare time.

The error with the variable `data` was an error from my side: A function called `data` is part of the plugin protocol. If a class has such an attribute, makejinja tries to execute it, leading to the observed error. Probably the safest way is to prefix all private attributes with an underscore.

**Comment by mirkolenz** [comment]
I finally had the time to tinker with it. I got it to work and given the makejinja output it seems to correctly apply the filters with my modifications. There are two changes that need to be done to the MWE:

1. The filter files were named `_mkfilter.py`, but the pattern matched `_mjfilter.py`. Thus, I renamed all filter files.
2. I used the following code for the plugin:

```python
import importlib.util
import sys
from collections.abc import Callable
from pathlib import Path
from typing import Any

import makejinja


def import_filter(file: Path) -> Callable[[dict[str, Any]], bool]:
    # https://docs.python.org/3/library/importlib.html#importing-a-source-file-directly

    module_path = file.relative_to(Path.cwd()).with_suffix("")
    module_name = str(module_path).replace("/", ".")
    spec = importlib.util.spec_from_file_location(module_name, file)

    assert spec is not None

    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module

    assert spec.loader is not None

    spec.loader.exec_module(module)

    return module.main


class Plugin(makejinja.plugin.Plugin):
    def __init__(self, data: dict[str, Any], config: makejinja.config.Config):
        self._data = data
        self._config = config

        self._excluded_dirs: set[Path] = set()

        for input_path in config.inputs:
            for filter_file in input_path.rglob("_mjfilter.py"):
                filter_func = import_filter(filter_file)
                if filter_func(data) is False:
                    self._excluded_dirs.add(filter_file.parent)

    def path_filters(self):
        return [self._mjfilter_func]

    def _mjfilter_func(self, path: Path) -> bool:
        # Render the file if there is no parent directory that is excluded
        return not any(
            path.is_relative_to(excluded_dir) for excluded_dir in self._excluded_dirs
        )

```

I did not get it to work using Jinja's `import_string` since this assumes that Python modules are imported. AFAIK, this only works if all "parent modules" include an `__init__.py` file which is not the case here. Thus, I resorted to an approach that is a bit more involved but seems to be the officially recommended way of dynamically importing arbitrary files.

<details>
<summary>Here is the output I got when running `makejinja` in the MWE (click to expand):</summary>

```txt
Load data './bootstrap/vars/config.yaml'
Create dir './bootstrap/templates/kubernetes' -> './kubernetes'
Create dir './bootstrap/templates/kubernetes/apps' -> 
'./kubernetes/apps'
Create dir './bootstrap/templates/kubernetes/apps/test0' -> 
'./kubernetes/apps/test0'
Create dir './bootstrap/templates/kubernetes/apps/test0/__pycache__' -> 
'./kubernetes/apps/test0/__pycache__'
Copy file './bootstrap/templates/kubernetes/apps/test0/__pycache__/_mjfilter.cpython-311.pyc' -> 
'./kubernetes/apps/test0/__pycache__/_mjfilter.cpython-311.pyc'
Skip excluded path './bootstrap/templates/kubernetes/apps/test0/_mjfilter.py'
Render file './bootstrap/templates/kubernetes/apps/test0/app.yaml.j2' -> 
'./kubernetes/apps/test0/app.yaml'
Create dir './bootstrap/templates/kubernetes/apps/test0/config' -> 
'./kubernetes/apps/test0/config'
Render file './bootstrap/templates/kubernetes/apps/test0/config/config.yaml.j2' -> 
'./kubernetes/apps/test0/config/config.yaml'
Skip excluded path './bootstrap/templates/kubernetes/apps/test1'
Skip excluded path './bootstrap/templates/kubernetes/apps/test1/__pycache__'
Skip excluded path './bootstrap/templates/kubernetes/apps/test1/__pycache__/_mjfilter.cpython-311.pyc'
Skip excluded path './bootstrap/templates/kubernetes/apps/test1/_mjfilter.py'
Skip excluded path './bootstrap/templates/kubernetes/apps/test1/app.yaml.j2'
Skip excluded path './bootstrap/templates/kubernetes/apps/test1/config'
Skip excluded path './bootstrap/templates/kubernetes/apps/test1/config/config.yaml.j2'
Create dir './bootstrap/templates/kubernetes/k0s' -> 
'./kubernetes/k0s'
Create dir './bootstrap/templates/kubernetes/k0s/__pycache__' -> 
'./kubernetes/k0s/__pycache__'
Copy file './bootstrap/templates/kubernetes/k0s/__pycache__/_mjfilter.cpython-311.pyc' -> 
'./kubernetes/k0s/__pycache__/_mjfilter.cpython-311.pyc'
Skip excluded path './bootstrap/templates/kubernetes/k0s/_mjfilter.py'
Create dir './bootstrap/templates/kubernetes/k0s/files' -> 
'./kubernetes/k0s/files'
Render file './bootstrap/templates/kubernetes/k0s/files/config.yaml.j2' -> 
'./kubernetes/k0s/files/config.yaml'
Render file './bootstrap/templates/kubernetes/k0s/k0s.yaml.j2' -> 
'./kubernetes/k0s/k0s.yaml'
Skip excluded path './bootstrap/templates/kubernetes/k3s'
Skip excluded path './bootstrap/templates/kubernetes/k3s/__pycache__'
Skip excluded path './bootstrap/templates/kubernetes/k3s/__pycache__/_mjfilter.cpython-311.pyc'
Skip excluded path './bootstrap/templates/kubernetes/k3s/_mjfilter.py'
Skip excluded path './bootstrap/templates/kubernetes/k3s/files'
Skip excluded path './bootstrap/templates/kubernetes/k3s/files/config.yaml.j2'
Skip excluded path './bootstrap/templates/kubernetes/k3s/k3s.yaml.j2'
Skip excluded path './bootstrap/templates/kubernetes/talos'
Skip excluded path './bootstrap/templates/kubernetes/talos/__pycache__'
Skip excluded path './bootstrap/templates/kubernetes/talos/__pycache__/_mjfilter.cpython-311.pyc'
Skip excluded path './bootstrap/templates/kubernetes/talos/_mjfilter.py'
Skip excluded path './bootstrap/templates/kubernetes/talos/files'
Skip excluded path './bootstrap/templates/kubernetes/talos/files/config.yaml.j2'
Skip excluded path './bootstrap/templates/kubernetes/talos/talos.yaml.j2'
Render file './bootstrap/templates/main.yaml.j2' -> 
'./main.yaml'
```
</details>

Please let me know if this code works for you.

**Comment by onedr0p** [comment]
Thank you so much for taking the time to look into this, I tried it out in my test repo and it appears to be working 🎉  I'll be giving it a try in my main repo soon and hopefully all goes well and does not speed down the execution drastically. This helps immensely with conditional based generation of folders and files, you have no idea how much of an effect this means in my project.

One note is I had to do was set an env var of `PYTHONDONTWRITEBYTECODE="1"` to have those pesky __pycache_ folders not be generated.

**Comment by onedr0p** [comment]
I am going to go ahead and close this issue since it is all working now. I honestly can't tell any speed difference as it still seems fast.

It would still be nice for makejinja to support this special file out of the box but I will take this win and again, I have so much gratitude for this project and you helping me out here.

**Comment by mirkolenz** [comment]
Thanks for the feedback, great that it works for you now! I agree that such a feature may be interesting for others in the future, but am a bit hesitant to integrate it into makejinja since there are a few potential parameters (e.g., the file name, the arguments passed to the functions). Another idea that I have would be to include the plugin code into makejinja so that it can be loaded by adding a module name like `makejinja.plugins.mjfilter` to the list of plugins in the config (the ability to offer such bundled plugins was the main reasons why plugin is a list and not a single entry). In that case however, no customization would be possible and anyone wanting to modify it would need to duplicate the code (which is not ideal IMHO). I will let you know once/if I made a decision on this matter.
