### ISSUE TITLE
Support specifying location of makejinja config file

### ISSUE THREAD

**Issue by onedr0p** [mirkolenz/makejinja#95]
**Is your feature request related to a problem? Please describe.**

I found myself needing to put the makejinja config file in a separate location, I noticed in the CLI help it says

> Instead of passing CLI options, you can also write them to a file called makejinja.toml in your working directory.

**Describe the solution you'd like**

I would love to put this file somewhere else and reference it in the `makejinja` CLI (e.g. `makejinja --config ./.github/makejinja.toml`)

This could be pretty sweet if you want to pass different config files for templating the same `input` but have slightly different data-vars or data config options.

```
makejinja --config ./test1/makejinja.toml
makejinja --config ./test1/makejinja-slightly-different-config-but-same-input.toml
```

I realize I could have makejinja config files in different directories and run it from there but that could mess up the pathing in the config file.

**Comment by onedr0p** [comment]
One last thought, running `makejinja --config ./test1/makejinja.toml` I would expect the input/output and other paths in the config file to be relative to where makejina was run from not `./test1`

**Comment by mirkolenz** [comment]
This is already supported :)

Internally, we use `typed-settings` to handle the `makejinja.toml` config file. It allows you to specify the config file location via [environment variables](https://typed-settings.readthedocs.io/en/latest/guides/config-files.html#dynamic-search-paths-via-environment-variables). For instance:

```shell
MAKEJINJA_SETTINGS=./test1/makejinja.toml makejinja
MAKEJINJA_SETTINGS=./test1/makejinja-slightly-different-config-but-same-input.toml makejinja
```

Providing an option like `makejinja --config` would be better since that would also be documented in the generated help screen, but from what I can see this is currently not possible.

I never tested overriding the config file location though, so feel free to reopen the issue if it does not work as expected.

**Comment by onedr0p** [comment]
Nice! I didn't know that env existed, however it looks like when specifying `MAKEJINJA_SETTINGS=./test1/makejinja.toml makejinja` the paths in the config file are relative to `./test1` which I expected but not what I am looking for.

**Comment by onedr0p** [comment]
I am unable to reopen the issue, if you think this is worth exploring it would be awesome to re-open.

**Comment by mirkolenz** [comment]
Thanks for letting me know. I am afraid there is not much I can do about the relative paths since I rely on the functionality of `typed-settings` here. Also, as a user I would expect that paths in a config file are parsed from its location and not from the current working directory of the shell (i.e., the way it behaves at the moment). Would it be a valid workaround for you to use paths like `../input` instead of `./input` here?

**Comment by onedr0p** [comment]
Yep that workaround should work, I just need to be cautious of I ever move the config file. I'll test and report back in a bit.
